# Arrays 

In [1]:
import numpy as np
import os

### 1d Array

In [2]:
import numpy as np
a = np.array([11,23,33])
a

array([11, 23, 33])

### 2d Array

In [3]:
dd = np.array([[1,2,2,3],[1,2,2,3],[1,2,3,4]])
dd

array([[1, 2, 2, 3],
       [1, 2, 2, 3],
       [1, 2, 3, 4]])

In [4]:
#Zero Array
b = np.zeros(2)
b

array([0., 0.])

In [5]:
#one's Array

c = np.ones(3)
c

array([1., 1., 1.])

In [6]:
#Empty Arrays
a = np.empty(3)
c

array([1., 1., 1.])

In [7]:
#Define to arrange
ran = np.arange(6)
ran

array([0, 1, 2, 3, 4, 5])

In [8]:
#Arrange specific
ran = np.arange(4,32)
ran

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [9]:
#Arrange with interval of any value
ran = np.arange(3,27, 3)
ran

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [10]:
#Define space lineraly
spc = np.linspace(0,100, num =3)
spc

array([  0.,  50., 100.])

In [11]:
#here array accept specific datatype(int)
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [12]:
#here 2d array accept specific datatype(int)
dd = np.ones((5,5), dtype=np.int8)
dd


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [13]:
#here array accept specific datatype(float)

g = np.zeros(4, dtype=np.float64)
g

array([0., 0., 0., 0.])

In [14]:
#here array accept specific datatype(float)

p = np.zeros((4,4), dtype = np.int8)
p

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [15]:
h = np.empty((2,3), dtype = np.float64)
h

array([[0., 0., 0.],
       [0., 0., 0.]])

### Create a 3d Array

In [16]:
c = np.arange(24).reshape(2,3,4)  #2Matrix, 3Rows, 4Column
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Concatenate Array

In [18]:
a = np.array([[1,2,3], [11,22,33]])
a

array([[ 1,  2,  3],
       [11, 22, 33]])

In [29]:
#write 0 if want to add y axis else 1
b = np.array([[22,33,44],[55,44,33]])
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3, 22, 33, 44],
       [11, 22, 33, 55, 44, 33]])

In [36]:
#check dimension of the array
c.ndim

2

In [37]:
#Check sizse(number of element in aray)

c.size

12

In [38]:
#Check seize(rows and columns)
c.shape

(2, 6)

In [66]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#Change rown in column and visa versa
b=a.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Conver 1d to 2d array

In [53]:
a = np.array([1,2,3,4,4,5,7])
a

array([1, 2, 3, 4, 4, 5, 7])

In [58]:
#Row vise 2d conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 4, 5, 7]])

In [61]:
#Column vise 2d converstion
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [7]])

# Indexing

In [79]:
a = np.array([[2,3,4,5],[4,3,2,0],[4,3,2,4]])
a

array([[2, 3, 4, 5],
       [4, 3, 2, 0],
       [4, 3, 2, 4]])

In [81]:
#find index
a[1]

array([4, 3, 2, 0])

In [83]:
#add 3 as intervel in the first two number
a = np.arange(10,20, 3)
a

array([10, 13, 16, 19])

### Adding, removing, and sorting elements

In [86]:
#Sort an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
# You can concatenate them with np.concatenate().
a = np.array([1, 2, 3, 4])

b = np.array([5, 6, 7, 8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
#Concatenate accor to axis
x = np.array([[1, 2, 2], [3, 4,4]])

y = np.array([[5, 6, 3]])

z = np.concatenate((x,y), axis=0)
z

array([[1, 2, 2],
       [3, 4, 4],
       [5, 6, 3]])

In [93]:
#How to know the shape of the array. 
array_example = np.array([[[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0 ,1 ,2, 3],

                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [96]:
np.ndim(array_example)

3

In [112]:
a = np.array([[[1,2,3,4],[4,5,6,7]],
              
              [[1,2,3,5],[4,5,6,7]]])
a

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 5],
        [4, 5, 6, 7]]])

In [113]:
#To find the size in array
a.size

16

In [115]:
#to find the shape
a.shape

(2, 2, 4)